spring:
  data:
    mongodb:
      uri: mongodb+srv://User_teste:Murdock@microblog-application.dbjo0y7.mongodb.net/microblog-application?retryWrites=true&w=majority

      auto-index-creation: true
  application:
    name: webflux-course