spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@microblog-application.dbjo0y7.mongodb.net/?retryWrites=true&w=majority&appName=${DB_NAME:webflux-course}
  application:
    name: webflux-course